# Generated by Django 4.2.6 on 2023-12-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chapter', models.CharField(max_length=100, verbose_name='наименование раздела')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_material', models.CharField(max_length=255, verbose_name='название')),
                ('description_material', models.TextField(verbose_name='описание')),
                ('video_link_material', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='вопрос')),
                ('answer_1', models.CharField(default=0, max_length=100, verbose_name='Ответ 1')),
                ('answer_2', models.CharField(default=0, max_length=100, verbose_name='Ответ 2')),
                ('answer_3', models.CharField(default=0, max_length=100, verbose_name='Ответ 3')),
                ('correct_answer', models.IntegerField(choices=[(1, 'Ответ 1'), (2, 'Ответ 2'), (3, 'Ответ 3')], default=0, verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(verbose_name='выбор')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.test', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'результат',
                'verbose_name_plural': 'результаты',
            },
        ),
    ]
