# Generated by Django 5.0 on 2023-12-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chapter', models.CharField(max_length=100, verbose_name='наименование раздела')),
                ('description_chapter', models.TextField(blank=True, null=True, verbose_name='описание раздела')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_material', models.CharField(max_length=255, verbose_name='название')),
                ('description_material', models.TextField(verbose_name='описание')),
                ('video_link_material', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.chapter', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
    ]
