# Generated by Django 4.2.6 on 2023-12-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='корректность ответа'),
        ),
    ]
