# Generated by Django 4.2.6 on 2023-12-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата'),
        ),
    ]
