# Generated by Django 4.2.6 on 2023-12-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'результат теста', 'verbose_name_plural': 'результаты тестов'},
        ),
    ]
